version: '3.8'

services:
  meilisearch:
    image: getmeili/meilisearch:v1.5
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey123}
      - MEILI_NO_ANALYTICS=true
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SERVICE_TYPE=api
      - MEILI_URL=http://meilisearch:7700
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey123}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./raw_json:/app/raw_json
    depends_on:
      meilisearch:
        condition: service_healthy
    restart: unless-stopped

  indexer:
    build: .
    volumes:
      - ./raw_json:/app/raw_json
    environment:
      - SERVICE_TYPE=indexer
      - MEILI_URL=http://meilisearch:7700
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey123}
      - DATA_DIR=/app/raw_json
      - PYTHONUNBUFFERED=1
    depends_on:
      meilisearch:
        condition: service_healthy
    restart: unless-stopped

volumes:
  meili_data: